[2022-10-29 03:21:55,763] {processor.py:153} INFO - Started process (PID=11537) to work on /opt/airflow/dags/init.py
[2022-10-29 03:21:55,792] {processor.py:641} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-10-29 03:21:55,809] {logging_mixin.py:115} INFO - [2022-10-29 03:21:55,809] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-10-29 03:21:56,633] {logging_mixin.py:115} INFO - [2022-10-29 03:21:56,340] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 6, in <module>
    from airflow.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 23, in <module>
    from airflow.hooks.subprocess import SubprocessHook
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 30, in <module>
    class SubprocessHook(BaseHook):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 30, in SubprocessHook
    class SubprocessHook(BaseHook):
SystemError: unknown opcode
[2022-10-29 03:21:56,648] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-10-29 03:21:57,353] {processor.py:161} INFO - Processing /opt/airflow/dags/init.py took 1.681 seconds
[2022-10-29 03:22:28,516] {processor.py:153} INFO - Started process (PID=11591) to work on /opt/airflow/dags/init.py
[2022-10-29 03:22:28,518] {processor.py:641} INFO - Processing file /opt/airflow/dags/init.py for tasks to queue
[2022-10-29 03:22:28,520] {logging_mixin.py:115} INFO - [2022-10-29 03:22:28,519] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/init.py
[2022-10-29 03:22:28,553] {logging_mixin.py:115} INFO - [2022-10-29 03:22:28,547] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/init.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init.py", line 6, in <module>
    from airflow.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 23, in <module>
    from airflow.hooks.subprocess import SubprocessHook
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 30, in <module>
    class SubprocessHook(BaseHook):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 30, in SubprocessHook
    class SubprocessHook(BaseHook):
SystemError: unknown opcode
[2022-10-29 03:22:28,554] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/init.py
[2022-10-29 03:22:28,606] {processor.py:161} INFO - Processing /opt/airflow/dags/init.py took 0.104 seconds
