[2022-10-29 03:21:55,731] {processor.py:153} INFO - Started process (PID=11538) to work on /opt/airflow/dags/transform_and_analysis.py
[2022-10-29 03:21:55,751] {processor.py:641} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2022-10-29 03:21:55,762] {logging_mixin.py:115} INFO - [2022-10-29 03:21:55,762] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2022-10-29 03:21:56,450] {logging_mixin.py:115} INFO - [2022-10-29 03:21:56,243] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 3, in <module>
    from airflow.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 23, in <module>
    from airflow.hooks.subprocess import SubprocessHook
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 30, in <module>
    class SubprocessHook(BaseHook):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 30, in SubprocessHook
    class SubprocessHook(BaseHook):
SystemError: unknown opcode
[2022-10-29 03:21:56,464] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2022-10-29 03:21:56,987] {processor.py:161} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 1.298 seconds
[2022-10-29 03:22:27,427] {processor.py:153} INFO - Started process (PID=11590) to work on /opt/airflow/dags/transform_and_analysis.py
[2022-10-29 03:22:27,428] {processor.py:641} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2022-10-29 03:22:27,429] {logging_mixin.py:115} INFO - [2022-10-29 03:22:27,429] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2022-10-29 03:22:27,472] {logging_mixin.py:115} INFO - [2022-10-29 03:22:27,464] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 3, in <module>
    from airflow.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 23, in <module>
    from airflow.hooks.subprocess import SubprocessHook
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 30, in <module>
    class SubprocessHook(BaseHook):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 30, in SubprocessHook
    class SubprocessHook(BaseHook):
SystemError: unknown opcode
[2022-10-29 03:22:27,473] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2022-10-29 03:22:27,505] {processor.py:161} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.082 seconds
